version: '3.8'
services:
    messaging-api:
        build:
            context: ./
            dockerfile: Dockerfile
        image: zyberfox-messaging
        ports:
            - "8080:8080"
        networks:
            - zyberfox-network
        depends_on:
            - messaging-db

    messaging-db:
        container_name: messaging-db
        image: postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_DB: messaging
            POSTGRES_PASSWORD: password
            PGDATA: /data/postgres
        #        volumes:
        #            - postgres:/data/postgres
        ports:
            - "5433:5432"
        networks:
            - zyberfox-network
        restart: always

#    messaging-pgadmin:
#        container_name: pgadmin
#        image: pgadmin4
#        environment:
#            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#            PGADMIN_CONFIG_SERVER_MODE: 'False'
#        volumes:
#            - pgadmin:/var/lib/pgadmin
#        ports:
#            - "5050:80"
#        networks:
#            - zyberfox-network
#        restart: unless-stopped

#    maildev:
#        image: maildev
#        restart: always
#        environment:
#            - TZ=Asia/Shanghai
#            - MAILDEV_WEB_PORT=1080
#            - MAILDEV_SMTP_PORT=1025
#        volumes:
#            - maildev:/home/maildev:rw
#        ports:
#            - "8080:1080"
#            - "8025:1025"
#        networks:
#            - zyberfox-network
#        logging:
#            driver: "json-file"
#            options:
#                max-size: "1m"

networks:
    zyberfox-network:
        driver: bridge

#volumes:
#    postgres: